language: php

sudo: false

matrix:
  include:
    - php: '5.3'
      dist: precise
    - php: '5.4'
      dist: trusty
    - php: '5.5'
      dist: trusty
    - php: '5.6'
      dist: trusty
    - php: '7.0'
      dist: trusty
    - php: '7.1'
      dist: xenial
    - php: '7.2'
      dist: xenial
    - php: '7.3'
      dist: xenial
    - php: nightly

before_script:
  - curl -sSfL -o ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install

script: phpunit
